# Generated by Django 2.2 on 2019-05-30 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='from_to',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
